### ISSUE TITLE
Since 8b65e3a1f8 sites/template.linux/conf/crontab_settings.txt no longer ends in a newline

### ISSUE THREAD

**Issue by mrenvoize** [mdnoble73/aspen-discovery#1007]
POSIX operating systems requires a trailing newline character to consider any line to be complete.

We lost said character with 8b65e3a1f8 and so when createSite is used to create a new site the cronfile it generates is faulty until someone manually edits it for the first time (nano, vim and most other editors all add this automatically add this character on save)

**Comment by mdnoble73** [comment]
You put in a PR for this, closing
