### ISSUE TITLE
Automatic location / library record ownership is broken in new installs

### ISSUE THREAD

**Issue by HitScan** [mdnoble73/aspen-discovery#1028]
In 23.01.00 the (location|library)_records_owned tables were removed and their purpose handled by (location|library)_records_to_include, which is great, but it looks like none of the java exporters were updated to reflect this change as this is dropped in the logs:

Error adding branch ABC to Aspen
java.sql.SQLSyntaxErrorException: Table 'aspen.location_records_owned' doesn't exist
...
I expect the fix is simple (modify the records to include statements to just set owned to 1, throw away references to records owned statements) but I haven't had a lot of luck yet getting IDEA to cooperate with building the various modules.

**Comment by mdnoble73** [comment]
This has been fixed in 23.03
