### ISSUE TITLE
Support for Chilifresh cover images

### ISSUE THREAD

**Issue by gmcharlt** [mdnoble73/aspen-discovery#1064]
I have a patch under way for adding Chilifresh as a provider of cover images that will turn into a pull request later this week.

This will be quite straightforward, as the Chilifresh cover service has the same concept as Syndetics, just a different URL structure. The main wrinkle is that the Chilifresh service can also accept OCLC numbers - and that makes a difference for resources such as board games that may not have either ISBN or UPC.

**Comment by mdnoble73** [comment]
Thanks for the heads up, if you need assistance, please let us know in slack
