### ISSUE TITLE
Multiple database updates fail due to MySQL limitations

### ISSUE THREAD

**Issue by HitScan** [mdnoble73/aspen-discovery#1078]
During an update from 23.02.00 to 23.03.00 I had multiple updates to the sso_settings table fail because of row size limits being exceeded. Is there a reason that 'VARCHAR(255)' is used as an essentially "unlimited" text entry size when the 'TEXT' data type will do the same thing without chewing up 255 of the 8126 byte row limit?

**Comment by mdnoble73** [comment]
Do you have more information about which columns failed? We are using that as convention for now, but if a column needs to be increased we can certainly look at changing column size.

**Comment by HitScan** [comment]
ssoILSUniqueAttribute, ldapHosts, ldapLabel, and ssoAuthOnly. Changing a few of the varcahr(255)'s to varchar(256) to kick them over into overflow storage suffices to allow the updates to run, but just replacing varchar(255) with TEXT would be a fix it and forget it forever change.

**Comment by mdnoble73** [comment]
We may want to look at reducing some of those column lengths instead. Several of those columns will never be 255 characters long.
