### ISSUE TITLE
Aspen needs a proper build system for the java modules

### ISSUE THREAD

**Issue by HitScan** [mdnoble73/aspen-discovery#1103]
From the look of it the only way to build the java modules is to use IntelliJ IDEA with a specific setup that's not present in the repository and is difficult to replicate. It's also making use of some com.sun.*.**internal** classes which is a bad idea. If a build system like Maven were in place it would be compatible with using IDEA but you could also more rapidly test fixes by rebuilding the .jar's on the server demonstrating an issue. It would also allow the repository to stop including the jars, slowing future disk space needs.

**Comment by HitScan** [comment]
It might also allow the dependancies to no longer be included directly in the repo.

**Comment by mdnoble73** [comment]
The developers who have been contributing Java updates are all good with the system we have in place now and it's worked just fine for the past 14 years.  We can certainly look into updates in the future, but won't do anything right away.  Happy to discuss more in slack if you wish.
