### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by minusdavid** [mdnoble73/aspen-discovery#114]
I am interested in installing Aspen Discovery, and I was hoping some installation instructions could be added to this repository. 

I noticed a a line in the README saying "For more information about setting up or contributing to Aspen Discovery, visit https://bywatersolutions.com/projects/aspen-discovery", but I didn't find any information about setting up or contributing on that page (or any linked page from there).

**Comment by bpnak** [comment]
@mdnoble73 is it planned for the nearest future?

**Comment by felipe-riobranco** [comment]
> Estou interessado em instalar o Aspen Discovery e esperava que algumas instruções de instalação pudessem ser adicionadas a este repositório.
> 
> Notei uma linha no LEIA-ME dizendo "Para obter mais informações sobre como configurar ou contribuir para o Aspen Discovery, visite https://bywatersolutions.com/projects/aspen-discovery", mas não encontrei nenhuma informação sobre como configurar ou contribuir nessa página (ou em qualquer página vinculada a partir daí).

@minusdavid Você conseguiu uma respostas satisfatória deles? Eu também gostaria de instalar o Aspen Discovery
