### ISSUE TITLE
Docs: Location IP Addresses - IP format options

### ISSUE THREAD

**Issue by StomproLARL2023** [mdnoble73/aspen-discovery#1623]
Hello, in the inline docs for the IP address format it just says "The IP Address to map to a location formatted as xxx.xxx.xxx.xxx/mask"

In the documentation on
https://help.aspendiscovery.org/ipaddresses

You can input either a single IP or a range of IPs. For example: 100.xxx.001-100.xxx.299

It would be nice to have consistency between the two locations.  Or at least have the main documentation go into more detail about all the formats allowed if there isn't room in the tooltip popup for all of it.

**Comment by mdnoble73** [comment]
I've updated the documentation within Aspen in version 24.02.  Thanks for the report.
