### ISSUE TITLE
Location IP Addresses - Add New - Save changes and return is the same as Save Changes and Add Another

### ISSUE THREAD

**Issue by StomproLARL2023** [mdnoble73/aspen-discovery#1624]
I noticed that both the 
Save Changes and Return button and Save Changes and Add Another button perform the same.  They both act like "Save Changes and Add Another"

It seems like for the first entry added, the buttons work correctly.  But then on the second one added, that is when the buttons start misbehaving.

Steps to Reproduce:

1. Open the Location IP Addresses admin page /Admin/IPAddresses?objectAction=list
2. Click Add New
3. Enter IP, Display Name and Location, Uncheck "Treat as Public Opac" and "Default log me out".
4. Click Save Changes and add another
5. Repeat the process to enter data.
6. Click Save Changes and Return
7. It behaves like you clicked Save Changes and Add Another - Loading /Admin/IPAddresses?sort=ip+asc&objectAction=addNew

Maybe the objectAction=addNew is getting added to the session attributes or something?

Minor issue, just something that I noticed when adding a bunch of entries.

**Comment by mdnoble73** [comment]
Thanks for the report.  This can be a bit confusing.  The Save and Return is trying to return you to your previous location rather than return you to the list. 99% that works the way it should, but every once in awhile Aspen can get a little confused.
