### ISSUE TITLE
option to manually renew items

### ISSUE THREAD

**Issue by gliptak** [mdnoble73/aspen-discovery#1714]
I would like to have the ability to renew items at any time before the due date. One might not be available to return an item exactly on due date. And renewing earlier also allows to align renew dates of multiple items (so needing to keep track fewer due dates)

running v. 24.02.04

**Comment by mdnoble73** [comment]
Hello, this works depending on the ILS.  What ILS are you using?

**Comment by mdnoble73** [comment]
You should also have an ILS like Koha, Evergreen, Sierra, Symphony, etc. Aspen Discovery is not a standalone solution.

**Comment by gliptak** [comment]
it is Koha

**Comment by mdnoble73** [comment]
Are you using auto renewals? And which version of Koha are you on? Newer versions of Koha are required to allow renewal if autorenewal is enabled.

**Comment by gliptak** [comment]
thank you @mdnoble73 yes, I was advised that enabling autorenewal disables manual renewal, the rational of which I don't follow at this point. I don't have Koha version details. considering that behaviour is backend driven, I'm closing this issue
