### ISSUE TITLE
Issue when install Aspen and connect with Koha

### ISSUE THREAD

**Issue by ahmed264** [mdnoble73/aspen-discovery#453]
Dears,

I finished setup Aspen in debian environment
But the search not working
I log file error couldn't connect with Koha database
 any help ?

**Comment by ahmed264** [comment]
I solved it 
Thanks

**Comment by sloneccls** [comment]
Were you getting an error with Solr? I'm getting this one:

**Error loading browse information**
Solr is not currently running

If that is the same one you were getting, could you tell us how you resolved it?
