### ISSUE TITLE
UpdateReadingHistory only for use with Horizon? For reals?

### ISSUE THREAD

**Issue by NashvillePublicLibrary** [mdnoble73/aspen-discovery#51]
The model config.cron.ini and all sites' config.cron.ini have a curious comment

https://github.com/mdnoble73/aspen-discovery/blob/53fbcd8d943fffa41833ca95e82798243e77874f/sites/model.localhost/conf/config.cron.ini#L23

surely that's not true...

**Comment by mdnoble73** [comment]
Fixed with commit: fcec55e4bf5af54e675a7a82f0ec23565650fd4b
