### ISSUE TITLE
Transition from Pika to Aspen

### ISSUE THREAD

**Issue by NashvillePublicLibrary** [mdnoble73/aspen-discovery#52]
Hardcoded Pika directories should be updated to Aspen-Discovery. 

Fetches from marmot servers should be removed.

**Comment by NashvillePublicLibrary** [comment]
FWIW there are numerous references to Pika that could [should?] be updated in the code. About 124 of them.

```
jstaub@hobvmplap07 /usr/local/aspen-discovery -  (20.07.00) $ grepa pika | wc -l
124

```

**Comment by mdnoble73** [comment]
See commit: d8bd0db6c19b6a37e71fbe70c9cea38e7bfa9bf7 

I believe this cleans up all references that should not be there. Please let me know if you see others that still need to be removed.

**Comment by NashvillePublicLibrary** [comment]
There are still hundreds of instances of 'pika', 'Pika', 'PIKA' - in comments, variable names and the such. Which is fine :)

**Comment by mdnoble73** [comment]
Marking this as done for now.  the remaining ones are required since they are things like conversion scripts.
