### ISSUE TITLE
Add the ability to specify Display Title and Display Author for a grouped work

### ISSUE THREAD

**Issue by mdnoble73** [mdnoble73/aspen-discovery#6]
Occasionally the display title and display author for a grouped work are not ideal because of capitalization or eContent providers giving different subtitle information than desired.  Allow staff to set the display title and display author so that capitalization and subtitles are set properly for a work.

**Comment by NashvillePublicLibrary** [comment]
@mdnoble73 Solved with https://github.com/mdnoble73/aspen-discovery/commit/17f67e927f4b16d56dbf731b8ec37f8109be3531 and subsequent commits https://github.com/mdnoble73/aspen-discovery/commit/a5f43ed887b3b3650c34d1a7da975fa77d65811f https://github.com/mdnoble73/aspen-discovery/commit/e11f09700e3934879ae259a151ceb625a0888b69

**Comment by mdnoble73** [comment]
This is done now as of 20.07
