### ISSUE TITLE
Change to rememberHoldPickupLocation in Koha.php breaks self reg

### ISSUE THREAD

**Issue by AndrewIsh** [mdnoble73/aspen-discovery#761]
A new addition to `Koha.php` introduced in https://github.com/mdnoble73/aspen-discovery/commit/eff6d20bde8e1a5d9ed41d5d7f62d09c85402d55 breaks self registration. [This line](https://github.com/mdnoble73/aspen-discovery/commit/eff6d20bde8e1a5d9ed41d5d7f62d09c85402d55#diff-ebd0bb54a381035aa6413cbf7bf882812e739554635d29626bf116fbac468095R933) sets the `rememberHoldPickupLocation` on the user object to `false`. The subsequent insert into `users` that results during self reg chokes as the SQL ends up with a `''` value for the `rememberHoldPickupLocation` column, which is not an integer, as expected by that column.

The fix is to change the line to `$user->rememberHoldPickupLocation = 0;`

**Comment by mdnoble73** [comment]
This has been corrected
